version: '3'

services:
  flask:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    volumes:
      - static:/static/

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static/
    depends_on:
      - flask
volumes:
  static: